export const theme = {
  colors: {
    primary: '#4F46E5',
    primaryLight: '#818CF8',
    primaryDark: '#3730A3',
    accent: '#EC4899',
    accentLight: '#F9A8D4',
    background: '#F5F7FB',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    text: '#111827',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    success: '#059669',
    successBackground: '#ECFDF5',
    warning: '#D97706',
    warningBackground: '#FFFBEB',
    error: '#DC2626',
    errorBackground: '#FEF2F2',
    info: '#2563EB',
    infoBackground: '#EFF6FF',
    heroStart: '#3730A3',
    heroEnd: '#4F46E5',
    promoBackground: '#EEF2FF',
    smartCartBackground: '#F0FDF4',
  },
  typography: {
    fontFamily: 'System',
    weights: {
      regular: '400' as const,
      medium: '500' as const,
      semiBold: '600' as const,
      bold: '700' as const,
      heavy: '800' as const,
    },
    sizes: {
      xs: 11,
      sm: 13,
      md: 15,
      lg: 17,
      xl: 20,
      xxl: 26,
      xxxl: 32,
    },
    letterSpacing: {
      tight: -0.3,
      normal: 0,
      wide: 0.3,
      caps: 1,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 32,
    xxl: 48,
  },
  radius: {
    small: 8,
    medium: 12,
    large: 16,
    xl: 20,
    pill: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    md: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.07,
      shadowRadius: 12,
      elevation: 3,
    },
    lg: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 6,
    },
  },
};
